# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: taskstealing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'taskstealing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12taskstealing.proto\"\x07\n\x05\x45mpty\"%\n\x13QueueLengthResponse\x12\x0e\n\x06length\x18\x01 \x01(\x05\"\x1c\n\x0b\x43PUResponse\x12\r\n\x05usage\x18\x01 \x01(\x05\"!\n\x10\x43PUUsageResponse\x12\r\n\x05usage\x18\x01 \x01(\x01\"&\n\x04Task\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x02\"4\n\x0cTaskResponse\x12\x13\n\x04task\x18\x01 \x01(\x0b\x32\x05.Task\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xac\x01\n\x13TaskStealingService\x12.\n\x0eGetQueueLength\x12\x06.Empty\x1a\x14.QueueLengthResponse\x12(\n\x0bGetCPUUsage\x12\x06.Empty\x1a\x11.CPUUsageResponse\x12\"\n\tStealTask\x12\x06.Empty\x1a\r.TaskResponse\x12\x17\n\x08SendTask\x12\x05.Task\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'taskstealing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_QUEUELENGTHRESPONSE']._serialized_start=31
  _globals['_QUEUELENGTHRESPONSE']._serialized_end=68
  _globals['_CPURESPONSE']._serialized_start=70
  _globals['_CPURESPONSE']._serialized_end=98
  _globals['_CPUUSAGERESPONSE']._serialized_start=100
  _globals['_CPUUSAGERESPONSE']._serialized_end=133
  _globals['_TASK']._serialized_start=135
  _globals['_TASK']._serialized_end=173
  _globals['_TASKRESPONSE']._serialized_start=175
  _globals['_TASKRESPONSE']._serialized_end=227
  _globals['_ACK']._serialized_start=229
  _globals['_ACK']._serialized_end=251
  _globals['_TASKSTEALINGSERVICE']._serialized_start=254
  _globals['_TASKSTEALINGSERVICE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
