# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import taskstealing_pb2 as taskstealing__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in taskstealing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskStealingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQueueLength = channel.unary_unary(
                '/TaskStealingService/GetQueueLength',
                request_serializer=taskstealing__pb2.Empty.SerializeToString,
                response_deserializer=taskstealing__pb2.QueueLengthResponse.FromString,
                _registered_method=True)
        self.GetCPUUsage = channel.unary_unary(
                '/TaskStealingService/GetCPUUsage',
                request_serializer=taskstealing__pb2.Empty.SerializeToString,
                response_deserializer=taskstealing__pb2.CPUUsageResponse.FromString,
                _registered_method=True)
        self.StealTask = channel.unary_unary(
                '/TaskStealingService/StealTask',
                request_serializer=taskstealing__pb2.Empty.SerializeToString,
                response_deserializer=taskstealing__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.SendTask = channel.unary_unary(
                '/TaskStealingService/SendTask',
                request_serializer=taskstealing__pb2.Task.SerializeToString,
                response_deserializer=taskstealing__pb2.Ack.FromString,
                _registered_method=True)


class TaskStealingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQueueLength(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCPUUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StealTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskStealingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQueueLength': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueLength,
                    request_deserializer=taskstealing__pb2.Empty.FromString,
                    response_serializer=taskstealing__pb2.QueueLengthResponse.SerializeToString,
            ),
            'GetCPUUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCPUUsage,
                    request_deserializer=taskstealing__pb2.Empty.FromString,
                    response_serializer=taskstealing__pb2.CPUUsageResponse.SerializeToString,
            ),
            'StealTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StealTask,
                    request_deserializer=taskstealing__pb2.Empty.FromString,
                    response_serializer=taskstealing__pb2.TaskResponse.SerializeToString,
            ),
            'SendTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTask,
                    request_deserializer=taskstealing__pb2.Task.FromString,
                    response_serializer=taskstealing__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TaskStealingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TaskStealingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskStealingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQueueLength(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskStealingService/GetQueueLength',
            taskstealing__pb2.Empty.SerializeToString,
            taskstealing__pb2.QueueLengthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCPUUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskStealingService/GetCPUUsage',
            taskstealing__pb2.Empty.SerializeToString,
            taskstealing__pb2.CPUUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StealTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskStealingService/StealTask',
            taskstealing__pb2.Empty.SerializeToString,
            taskstealing__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskStealingService/SendTask',
            taskstealing__pb2.Task.SerializeToString,
            taskstealing__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
